CREATE TABLE users (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    age INTEGER NOT NULL,

    CONSTRAINT pk_id PRIMARY KEY(id),
    CONSTRAINT unique_email UNIQUE(email)
)